### ISSUE TITLE
content-type header is not sent

### ISSUE THREAD

**Issue by hedgepigdaniel** [maraisr/fgs#1]
The `Content-type: application/json` header is a requirement for many servers, and should be sent as part of the introspection query

**Comment by maraisr** [comment]
Hi 👋🏻 

Thanks for the issue. Great point. However ive left this up to the graphql-config file for the user to define this.

The spec stipulates a new [`application/graphql+json`](https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#content-types) header — so cannot assume this.

You could do this;

> .graphqlconfig.json

```json
{
  "projects": {
    "webapi": {
      "schemaPath": "data/webapi.schema.graphql",
      "extensions": {
        "endpoints": {
          "dev": {
            "url": "https://api.graphql.online/web/api/graphql",
            "headers": {
              "content-type": "application/json"
            }
          }
        }
      }
    }
  }
}
```

**Comment by maraisr** [comment]
That being said, I could quite possible provide this header as a default — unless the user decides to change it 🤝

**Comment by theKashey** [comment]
`application/json` is a default content type of other is not configured.
Buried somewhere very deeply, so one need to use some defaults here, or delegate responsibility to `UrlLoader`
https://github.com/ardatan/graphql-tools/blob/master/packages/loaders/url/src/index.ts#L375

**Comment by maraisr** [comment]
schema loading is for sure a very deep concept, could go from this library (the basic and very enterprise friendly case) all the way to graphql codgegen for local schema files etc.

Using something like url-loader has cross my mind before, but there is an entire eco-system surrounding that, so if you need that level of complexity. Better to use that eco system entirely. 

---

that being said, I have release fgs@0.1.2 that will default the content-type to `application/graphql+json`. Should your server deviate from the specification or own case, the solution above can override that.
